"""Zentrale visuelle Konstanten für die SplatTricia-Oberfläche."""

# Gemeinsame Grundpalette der Stereo-Tools und Website-Projekte.
BG_MAIN = "#111111"
BG_SOFT = "#181818"
PANEL = "#202020"
PANEL_HOVER = "#282828"
BORDER = "#333333"

TEXT = "#f2f2f2"
TEXT_MUTED = "#b8b8b8"
TEXT_DISABLED = "#727272"

GOLD = "#9c7c38"
GOLD_LIGHT = "#c6a95e"

INPUT_BG = BG_SOFT
BUTTON_BG = BG_SOFT
BUTTON_HOVER = PANEL_HOVER

SLIDER_TRACK = BORDER
SLIDER_PROGRESS = GOLD
SLIDER_BUTTON = GOLD_LIGHT
SLIDER_BUTTON_HOVER = GOLD_LIGHT
SLIDER_DISABLED_PROGRESS = BORDER
SLIDER_DISABLED_BUTTON = TEXT_DISABLED
CHECKBOX_DISABLED = TEXT_DISABLED
PROGRESS_TRACK = BORDER

START_BG = BUTTON_BG
START_HOVER_BG = GOLD_LIGHT
START_TEXT = GOLD_LIGHT
START_HOVER_TEXT = BG_MAIN
START_BORDER = GOLD
START_HOVER_BORDER = GOLD_LIGHT
START_DISABLED_BG = BUTTON_BG
START_DISABLED_TEXT = TEXT_DISABLED
START_DISABLED_BORDER = BORDER

LANGUAGE_BG = PANEL
LANGUAGE_BUTTON_BG = PANEL_HOVER
LANGUAGE_HOVER = BORDER
LANGUAGE_DROPDOWN_BG = BG_SOFT
LANGUAGE_DROPDOWN_HOVER = PANEL_HOVER

DANGER = "#7f3939"
DANGER_HOVER = "#944545"

PREVIEW_BG = "#000000"

FONT_FAMILY = "Segoe UI"
RADIUS_CONTROL = 8
RADIUS_PANEL = 12
BORDER_WIDTH = 1
